package dev.quochung2003.reactiveLearning.helper;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;
import org.springframework.lang.NonNull;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Mono;

@Component
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class MailHelper {

    /**
     * Check if {@code typedOtp} is the same value with {@code providedOtp}.
     * @param providedOtp OTP that usually generated by {@link Math#random() random()} method.
     * @param typedOtp OTP typed by user.
     * @return A successful {@link Mono} emits with value {@code true} if these two fields has the same value, otherwise emits {@code false}.
     */
    @NonNull
    public Mono<Boolean> validateOtp(final String providedOtp, final @NonNull String typedOtp) {
        return Mono.just(typedOtp.equals(providedOtp));
    }
}
